/**
 * # Encryptor: Secure Token Generation and Verification System
 * 
 * Encryptor provides RSA-based cryptographic utilities for creating and verifying
 * secure tokens. It extends NodeRSA to offer simplified token generation and validation
 * for authentication and authorization workflows.
 * 
 * The system uses asymmetric cryptography for:
 * - Creating signed tokens containing arbitrary payloads
 * - Verifying token authenticity through signature validation
 * - Managing RSA key pairs with automatic key generation
 * 
 * This implementation is ideal for stateless authentication systems, API authorization,
 * secure data exchange between services, or any scenario requiring cryptographic
 * verification of data integrity and origin.
 */
import { readFile, writeFile } from "fs/promises"
import { existsSync } from "node:fs"
import NodeRSA from "node-rsa"

/**
 * Cryptographic utility for token generation and verification using RSA.
 * Extends NodeRSA to provide higher-level functions for working with signed tokens
 * that can contain any serializable data payload.
 */
export default class Encryptor extends NodeRSA {

    /**
     * Creates and initializes an Encryptor instance with an existing private key or generates a new one.
     * This factory method handles key generation, persistence, and instance creation in one operation.
     * 
     * If a key exists at the specified path, it loads and uses that key.
     * If no key exists, it generates a new 2048-bit RSA key and saves it to the provided path.
     * 
     * @param privateKeyPath The filesystem path where the private key is stored or should be created
     * @returns A configured Encryptor instance ready for token operations
     * 
     * @example
     * 
     * const encryptor = await Encryptor.initialize("/path/to/private-key.pem")
     * // The encryptor is now ready to create and verify tokens
     */
    public static async initialize(privateKeyPath: string) {

        let encryptor: Encryptor

        // Check if the private key file already exists
        if (existsSync(privateKeyPath)) {

            // Load the existing key from the file
            encryptor = new this(await readFile(privateKeyPath, "utf-8"))
        }

        else {

            // No key exists, so generate a new 2048-bit RSA key
            encryptor = new this({ b: 2048 })

            // Save the newly generated key to the specified path
            await writeFile(privateKeyPath, encryptor.exportKey("pkcs1-private-pem"))
        }

        // Return the configured encryptor instance
        return encryptor
    }

    /**
     * Creates a signed token containing the provided payload.
     * The token format follows a simplified JWT-like structure of "{encoded_payload}.{signature}"
     * where the payload is base64-encoded JSON and the signature is a base64-encoded RSA signature.
     * 
     * This method:
     * 1. Serializes and encodes the payload
     * 2. Creates a cryptographic signature of the encoded payload
     * 3. Combines them into a portable, verifiable token string
     * 
     * @param payload Any serializable data to include in the token
     * @returns A signed token string in the format "encoded_payload.signature"
     * 
     * @example
     * 
     * const token = encryptor.createToken({ userId: 123, role: "admin" })
     * // Returns a string like "eyJwYXlsb2FkIjp7InVzZX...FyTxp4n2K0="
     */
    public createToken(payload: unknown): string {

        // Serialize the payload to JSON and encode it to base64
        const encode = btoa(JSON.stringify({ payload }))

        // Generate a cryptographic signature for the encoded payload
        const signature = this.sign(encode, "base64")

        // Combine the encoded payload and signature with a dot separator
        return `${encode}.${signature}`
    }

    /**
     * Verifies a token's authenticity and extracts its payload.
     * This method validates that the token was created by a system with the corresponding private key
     * and has not been tampered with since creation.
     * 
     * The verification process:
     * 1. Splits the token into payload and signature components
     * 2. Verifies the signature against the payload using RSA
     * 3. Decodes and deserializes the full token structure if verification succeeds
     * 
     * @param token A token string previously generated by createToken()
     * @returns A Reference object containing the payload, or false if verification fails
     * 
     * @example
     * 
     * const result = encryptor.verifyToken<UserData>(token)
     * if (result) {
     *   // result.payload contains the original data: { userId: 123, role: "admin" }
     * } else {
     *   // Handle invalid token
     * }
     */
    public verifyToken<Payload>(token: string): Reference<Payload> | false {

        // Split the token into its two components: encoded payload and signature
        const [encode, signature] = token.split(".")

        // Convert the base64 signature to a Buffer for verification
        const bufferSignature = Buffer.from(signature, "base64")

        // Verify that the signature matches the encoded payload
        // If verification fails, return false to indicate an invalid token
        if (!this.verify(encode, bufferSignature)) return false

        return JSON.parse(atob(encode))
    }
}

/**
 * Represents the structure of a verified token containing the original payload.
 * This interface wraps the decoded token payload to maintain type safety
 * and provide a consistent return format from the verifyToken method.
 * 
 * @template Payload The type of the original data that was encoded in the token
 */
export interface Reference<Payload> {
    /** The original payload data that was encoded in the token */
    payload: Payload
}